### ISSUE TITLE
Custom Script - entity without type

### ISSUE THREAD

**Issue by Oliver2Goetz** [OpenCAGE/CathodeLib#1]
Hey Matt,

I tried out the custom scripting with C# and encountered an error. I had this problem while trying out own scripts but it seems like the spawning a player from the example code doesn't really work.
When the entity gets created, it has no type:
![image](https://user-images.githubusercontent.com/44117499/210459517-7239621f-519c-4f51-935e-c97528755dc1.png)

I use the example code from your documentation. This happens with my own code and the example code. I use is as followed (only the path of the COMMANDS.PAK has been edited):
```
public static void Main() {
    Commands commands = new Commands(rootDirectory + "DATA/ENV/PRODUCTION/ENG_ALIEN_NEST/WORLD/COMMANDS.PAK");
    Composite composite = commands.EntryPoints[0];
    composite.functions.Clear();

    FunctionEntity checkpoint = composite.AddFunction(FunctionType.Checkpoint);
    FunctionEntity playerSpawn = composite.AddFunction("ARCHETYPES\\SCRIPT\\MISSION\\SPAWNPOSITIONSELECT");

    checkpoint.AddParameter("is_first_checkpoint", new cBool(true));
    checkpoint.AddParameter("section", new cString("Entry"));
    checkpoint.AddParameterLink("finished_loading", playerSpawn, "SpawnPlayer");

    commands.Save();
}
```

Ingame my result was a black screen. I can pause the game or use the map, but that's about it. No radial menu or anything else.
Do I miss something obvious? Should I be able to use the radial menu?

I have CathodeLib 0.3.1 installed with .NET Framework 4.7.2

**Comment by MattFiler** [comment]
Glad you're giving this a go! I spotted an error with the documentation earlier, I think you must've followed along before I corrected it.

Change
```
composite.AddFunction("ARCHETYPES\\SCRIPT\\MISSION\\SPAWNPOSITIONSELECT");
```

to:

```
composite.AddFunction(commands.GetComposite("ARCHETYPES\\SCRIPT\\MISSION\\SPAWNPOSITIONSELECT"));
```

Hope that makes sense!

Also - please make sure you're using CathodeLib 0.3.2 that just got released, I spotted a rogue but potentially severe crash bug with 0.3.1 which should now be fixed!

**Comment by Oliver2Goetz** [comment]
Oh nice, that fixed it! Yes I had the older version of the documentation open.
The problem is comprehensible.
Updated to CathodeLib 0.3.2 just now.

**Comment by MattFiler** [comment]
Nice one! I'll remove the function which is allowing that confusion to occur. Glad the updated docs helped :)
